Badly placed ()'s.
Traceback (most recent call last):
  File "marginalization.py", line 412, in <module>
    testProbabilities = pd.read_csv('./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv')#GIS DATA WHICH SHOULD BE READ ONCE AND USED MULTIPLE TIMES
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv' does not exist: b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv'
Traceback (most recent call last):
  File "marginalization.py", line 412, in <module>
    testProbabilities = pd.read_csv('./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv')#GIS DATA WHICH SHOULD BE READ ONCE AND USED MULTIPLE TIMES
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv' does not exist: b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv'
Traceback (most recent call last):
  File "marginalization.py", line 412, in <module>
    testProbabilities = pd.read_csv('./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv')#GIS DATA WHICH SHOULD BE READ ONCE AND USED MULTIPLE TIMES
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv' does not exist: b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv'
Traceback (most recent call last):
  File "marginalization.py", line 412, in <module>
    testProbabilities = pd.read_csv('./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv')#GIS DATA WHICH SHOULD BE READ ONCE AND USED MULTIPLE TIMES
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv' does not exist: b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv'
Traceback (most recent call last):
  File "marginalization.py", line 412, in <module>
    testProbabilities = pd.read_csv('./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv')#GIS DATA WHICH SHOULD BE READ ONCE AND USED MULTIPLE TIMES
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv' does not exist: b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv'
Traceback (most recent call last):
  File "marginalization.py", line 412, in <module>
    testProbabilities = pd.read_csv('./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv')#GIS DATA WHICH SHOULD BE READ ONCE AND USED MULTIPLE TIMES
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv' does not exist: b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv'
Traceback (most recent call last):
  File "marginalization.py", line 412, in <module>
    testProbabilities = pd.read_csv('./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv')#GIS DATA WHICH SHOULD BE READ ONCE AND USED MULTIPLE TIMES
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv' does not exist: b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv'
Traceback (most recent call last):
  File "marginalization.py", line 412, in <module>
    testProbabilities = pd.read_csv('./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv')#GIS DATA WHICH SHOULD BE READ ONCE AND USED MULTIPLE TIMES
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv' does not exist: b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv'
Traceback (most recent call last):
  File "marginalization.py", line 412, in <module>
    testProbabilities = pd.read_csv('./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv')#GIS DATA WHICH SHOULD BE READ ONCE AND USED MULTIPLE TIMES
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv' does not exist: b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv'
Traceback (most recent call last):
  File "marginalization.py", line 412, in <module>
    testProbabilities = pd.read_csv('./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv')#GIS DATA WHICH SHOULD BE READ ONCE AND USED MULTIPLE TIMES
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/cm/shared/uaapps/anaconda/2019.07/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv' does not exist: b'./results/seattle_marginal_probabilities_init_inf=[0]_BETA=3.0_MU=140_EPS=0.5.csv'
